# Generated by Django 3.2.14 on 2022-11-20 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0002_choice_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='pub_date',
        ),
    ]
