# Generated by Django 3.2.14 on 2022-11-20 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0005_proyecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='portada',
            field=models.ImageField(null=True, upload_to='static/img/', verbose_name='Portada'),
        ),
    ]
