# Generated by Django 3.2.14 on 2022-11-20 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0007_auto_20221120_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='anio',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='nombre_slug',
        ),
    ]
