# Generated by Django 3.2.14 on 2022-11-21 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0009_auto_20221120_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='foto',
            field=models.ImageField(null=True, upload_to='static/img/', verbose_name='Foto'),
        ),
    ]
