# Generated by Django 3.2.14 on 2022-11-21 14:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('turnos', '0011_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Noticia',
        ),
    ]
